name: Documentation Issue
description: Report incorrect, missing, or confusing documentation
title: "[Docs]: "
labels: ["documentation", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Help us improve our documentation! Please fill out the form below.

  - type: dropdown
    id: type
    attributes:
      label: Documentation Type
      description: What kind of documentation issue is this?
      options:
        - Incorrect information
        - Missing information
        - Confusing or unclear
        - Typo or grammar
        - Broken link
        - Missing example
        - Outdated information
        - Accessibility issue
        - Other
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location
      description: Where is the documentation issue? (URL, file path, or section name)
      placeholder: e.g., /docs/wiki/getting-started.md or README.md#installation
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Documentation
      description: What does the documentation currently say? (Quote relevant parts)

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What's wrong with the current documentation?
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to improve this documentation?
      options:
        - label: I am willing to submit a pull request with improved documentation
