name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

        **Note**: For major features, please start a Discussion first to gauge
        community interest before creating an issue.

  - type: checkboxes
    id: preflight
    attributes:
      label: Preflight Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues and discussions for this feature
          required: true
        - label: This feature aligns with the project's goals
          required: true
        - label: This feature does not require Python, Node.js, or TypeScript
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Anti-convergence mechanisms
        - Metrics and emergence detection
        - Accessibility improvements
        - Security enhancements
        - Documentation
        - CI/CD and automation
        - Visualisation
        - Philosophical framework
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your request related to a problem?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: |
        If you have thoughts on how this could be implemented, share them here.
        This is optional but helps assess feasibility.

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How many users would benefit from this feature?
      options:
        - Low - Nice to have for specific use cases
        - Medium - Useful for many users
        - High - Essential for the project's success
    validations:
      required: true

  - type: dropdown
    id: effort
    attributes:
      label: Estimated Effort
      description: How much work do you think this would take?
      options:
        - Small - A few hours
        - Medium - A few days
        - Large - A week or more
        - Unknown - Not sure

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to implement this feature?
      options:
        - label: I am willing to submit a pull request for this feature
